### ISSUE TITLE
Umbrella issue for v1.0.0☂

### ISSUE THREAD

**Issue by kamiazya** [ts-graphviz/ts-graphviz#591]
# Summary

This issue is an umbrella for the next release of `ts-graphviz` and `@ts-graphviz/*`. 

We might add more issues to the issues to fix list.

## Pull Requests

- #551 
- #598
- #613
- #611
- #608 
- #616
- #619 

### Feature

- #542 
- #597

### Monorepolize

- #590 
- #593
- #594 
- #595 
- #596

### CI/CD

- #599
- #609
- #610
- #614

### Other

- #612
- #615
- #618
- #622

### Documentation

- #600 
- #601 

## Consideration

- [ ] Whether to leave a dependency on all-contributors-cli
- [ ] Whether to leave a dependency on lerna
- [ ] Introducing yarn v2
- [ ] Whether to select [ts-standard](https://github.com/standard/ts-standard) for code formatting
- [ ] Accelerate testing
- [ ] Provide AST walker
- [ ] Consider the possibility of using WeekMap for memory efficiency

## Packages structure plan [TBD]

The upper layer has a higher degree of abstraction.

- Domain knowledge
  - `@ts-graphviz/dot-type` - DOT attribute type **New**
  - `@ts-graphviz/dot-attribute` - DOT attributes **New**
  - `@ts-graphviz/dot-ast` -DOT language AST(Abstract Syntax Tree)  **New**
- Domain Model
  - `@ts-graphviz/model` - Object Oriented DOT Language Model. **New**
  - `@ts-graphviz/parser` - Parser for DOT Language text.
  - `@ts-graphviz/renderer` - DOT Renderer for AST. **New**
- Usecase/Presentation
  - `ts-graphviz`
  - `@ts-graphviz/node`
  - `@ts-graphviz/react`

**Comment by kamiazya** [comment]
The monorepo made tests and builds more complicated and increased development costs.
Once the plan is blank, reconsider how the project should be.
